#!/bin/sh

ICONV_CUE_F=
ICONV_CUE_T=UTF8

while getopts 'hc:' OPTION
do
    case $OPTION in
    c)
        ICONV_CUE_F=$OPTARG
        ;;
    h)
        printf "Usage: %s: [-c cue_encoding]\n" $(basename $0) >&2
        exit 2
        ;;
    esac
done

DISKNUM=
test_disk_image() {
    DISKNUM=`echo "$1" | perl -pe 's/.*(?:cd|disk)\s*(\d+).*/$1/i'`
    if [ "x$DISKNUM" = "x$1" ]; then
        DISKNUM=""
    fi
}


BASEDIR=${PWD}
SAVEIFS=$IFS
IFS='\n'
WORKDIR=.tmp-split-cue-flac

find ./ -name '*.flac' -size +100M |  while read image
do
    echo "$image"
    DIR=`dirname "$image"`
    BASE=`basename "$image"`
    BASE=`echo "$BASE" | sed -e 's/.flac//'`
    CUE=$BASE.cue
    IMAGE=$BASE.flac

    cd "$DIR"
        echo "Splitting with shnsplit"
        rm -rf $WORKDIR
        mkdir $WORKDIR

        if [ "x$ICONV_CUE_F" != "x" ]; then
           echo "Converting cue $CUE"
           iconv -f $ICONV_CUE_F -t $ICONV_CUE_T "$CUE" -o "$WORKDIR/$CUE"
        else
           cp "$CUE" "$WORKDIR/$CUE"
        fi && \

        shnsplit -d $WORKDIR -o flac -f "$WORKDIR/$CUE" -t "%n – %t" "$IMAGE" && \

        echo "Moving $IMAGE -> ${IMAGE}.image" && \
        mv "$IMAGE" "${IMAGE}.image" && \

        echo "Fixing tags with cuetag" && \
        cuetag "$WORKDIR/$CUE" ./$WORKDIR/*.flac && \

        test_disk_image "$IMAGE" && \

        DSK= && \
        if [ "x$DISKNUM" != "x" ]; then
            DSK="CD$DISKNUM"
            echo "Creating $DSK dir"
            rm -rf $DSK
            mkdir $DSK
        fi && \

        mv $WORKDIR/*.flac ./$DSK && \

        rm -r $WORKDIR

    if [ "x$DIR" != "x." ]; then
        cd "$BASEDIR"
    fi
done
IFS=$SAVEIFS

